version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}.0'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: 51VY02PYxX2TCuoS5VRvwZoTPvEMVTWyRnnHfa73Rj8Q0E5dzlZoUnSDmotw9d7S
  on:
    branch: master